[workspace]
members = [
    "crates/gml-cli/cli",
    "crates/gml-cli/core",
    "crates/gml-cli/daemon",
    "crates/gml-cli/lambda",
    "crates/gml-operator",
    "crates/gml-scheduler",
]
resolver = "2"
