[package]
name = "gml-daemon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gmld"
path = "src/main.rs"

[dependencies]
gml-core = { path = "../core" }
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"

